### ISSUE TITLE
Build failure on openSUSE Leap 42.3

### ISSUE THREAD

**Issue by tpbaker** [pabr/leansdr#11]
I get errors when attempting to compile , , odd.

g++ -O3 -I.. -Wall -Wno-sign-compare -Wno-array-bounds -Wno-unused-variable -DGUI leandvb.cc -lX11 -o leandvb  ||  \
g++ -O3 -I.. -Wall -Wno-sign-compare -Wno-array-bounds -Wno-unused-variable       leandvb.cc       -o leandvb
/tmp/ccaWZX5A.o:(.rodata._ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE[_ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE]+0x10): undefined reference to `leansdr::viterbi_dec_interface<unsigned char, unsigned char, int, int>::update(int*, int*)'
/tmp/ccaWZX5A.o:(.rodata._ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE[_ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE]+0x18): undefined reference to `leansdr::viterbi_dec_interface<unsigned char, unsigned char, int, int>::update(unsigned char, int, int*)'
collect2: error: ld returned 1 exit status
/tmp/ccU7EsXK.o:(.rodata._ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE[_ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE]+0x10): undefined reference to `leansdr::viterbi_dec_interface<unsigned char, unsigned char, int, int>::update(int*, int*)'
/tmp/ccU7EsXK.o:(.rodata._ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE[_ZTVN7leansdr21viterbi_dec_interfaceIhhiiEE]+0x18): undefined reference to `leansdr::viterbi_dec_interface<unsigned char, unsigned char, int, int>::update(unsigned char, int, int*)'
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'leandvb' failed
make: *** [leandvb] Error 1
tim@linux-8m91:~/src/leansdr/src/apps> gcc --version
gcc (SUSE Linux) 4.8.5

**Comment by pabr** [comment]
Should be fixed now (tested with gcc 4.6.3), please confirm.

**Comment by tpbaker** [comment]
Confirmed fixed. Just compiled with zero errors. Thanks much !
