### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ad6sh** [pabr/leansdr#2]
could you please tell how to run the gui of leandvb

**Comment by pabr** [comment]
Compile on a host with X11 development libraries; start with --gui.
Note: The gui is a debugging tool, not a replacement for command-line options.

**Comment by ad6sh** [comment]
Than you so much!. We have seen the sinal transmitted in spectrum analyzer..but the bandwidth is about 2Mhz.The signal constellation contains large amount of noise also.could you please help to solve the problem??

**Comment by ad6sh** [comment]
SORRY,THE BANDWIDTH IS ABOUT 2OMhz

**Comment by pabr** [comment]
Sample at 24 MHz or more.
Configure --f, --sr, --cr to match the parameters of the signal and the settings of the receiver.
Run "leandvb -v" and check in the output that the parameters are OK.
Record to a file and run leandvb offline.
If you see a QPSK constellation but too much noise, add "--sampler rrc --viterbi".

**Comment by ad6sh** [comment]
Symbol rate 125ksymbols/sec ,fec 7/8,pid 255,gain 5 ,i've set like this transmitter side and got 8MHz , i've mailed the photos,please do go through it
