### ISSUE TITLE
Compile: libiio and X11 not found

### ISSUE THREAD

**Issue by OZ1SEJ** [pabr/leansdr#21]
When I compile leandvb, I get these notifications:

    libiio not found. Will not build leaniio{rx,tx}.
    X11 not found. Will not compile GUI.

How do I resolve these? (Ubuntu 19.04)

**Comment by pabr** [comment]
You should now have a working "leandvb" binary anyway, except that it won't support the "--gui" command-line flag. For this you probably need to install a Ubuntu package called "libx11-dev" or something similar.

leaniiorx and leaniiotx are distinc applications, not required for leandvb.

**Comment by pabr** [comment]
You should now have a working "leandvb" binary anyway, except that it won't support the "--gui" command-line flag. For this you probably need to install a Ubuntu package called "libx11-dev" or something similar.

leaniiorx and leaniiotx are distinct applications, not required for leandvb.

**Comment by OZ1SEJ** [comment]
Ah, libx11-dev worked - thanks!
