### ISSUE TITLE
Which SDR transmitter works with the leandvb receiver?

### ISSUE THREAD

**Issue by VDelport** [pabr/leansdr#25]
Hello, I am trying to transmit an MPEG-TS with gr-dvbs2 as the transmitter and an rtl-sdr + leandvb as the receiver. I get an almost perfect constellation diagram. The MER is approx. 18 dB. But leandvb does not generate a transport stream. Have you tested leandvb yourself with gr-dvbs2tx? Do leandvb_tx and leandvb_rx work together? That doesn't work for me either.
Best regards.

**Comment by pabr** [comment]
Here is the simplest DVB-S2 test you can run:
> make leantsgen leandvbtx leandvb
> ./leantsgen | ./leandvbtx --standard DVB-S2 | ./leandvb --standard DVB-S2 --f32 -f 4e6 --gui -d > /dev/null

You should see a QPSK constellation for signalling, a 8PSK constellation for data, and a steady stream of '_' characters on stderr indicating good frames.

This will rule out compiler/portability issues. Then you can give more details about your use case, command-line parameters, etc.

**Comment by VDelport** [comment]
Thank you for your quick reply. The command line fails for me. leandvbtx and leandvb seem to have no option -- standard DVB-S2:

./leantsgen | ./leandvbtx --standard DVB-S2
...
** Error while processing '--standard'

  ./leandvb --help:
...
  --standard S DVB-S (default), DVB-S2 (not implemented)

**Comment by pabr** [comment]
Most likely, you need to run `git checkout work` or restart from scratch with `git clone -b work ...`. Also read http://www.pabr.org/radio/leandvb/leandvb.en.html#install about enabling S2 in the Makefile.

**Comment by VDelport** [comment]
Thank you very much, it works now, even with ffmeg in the pipe, to generate a transport stream from an mp4 file. Well, leandvb works in the baseband, and I would now like to implement a radio transmission using SDR devices. Can you give me a command lines that works with hackrf_transfer + leandvbtx as the transmitter and with hackr_transfer or rtl-sdr + leandvb as the receiver?

**Comment by pabr** [comment]
It looks like hackrf_transfer expects 8-bit signed ints whereas leandvbtx supports only 16-bit signed ints and 32-bit floats, so it won't work out-of-the-box.

For reception with rtl-sdr there are examples at http://www.pabr.org/radio/qo100sdr .

**Comment by VDelport** [comment]
Many thanks for your response. I was now able to successfully test the radio transmission with gr-dvbs2 (github.com/drmpeg/gr-dvbs2) and Hack-RF One as the transmitter and with leandvb and RTL-SDR as the receiver. Thank you for your support and the great project. :) Best regards.
