### ISSUE TITLE
Leandvb output UDP

### ISSUE THREAD

**Issue by f4dvk** [pabr/leansdr#37]
Hello,

Is it possible to direct the TS signal to a UDP address?
Example of UDP operation:
https://github.com/BritishAmateurTelevisionClub/longmynd

Thank you,
Stephane.

**Comment by pabr** [comment]
No, UDP output is not currently implemented. Some users pipe leandvb output into another command-line tool (tsduck ?) to split the TS into 188-byte chunks and send them over UDP.

**Comment by pabr** [comment]
Oh well, it's implemented now. Try "leandvb --ts-udp IPADDR:PORT". Tested with "mplayer udp://127.0.0.1:4000".

**Comment by F5OEO** [comment]
Nice, but warn : TS over UDP is generally standardized with a fixed payload of 7*TSpackets to fit in an ethernet frame.

**Comment by pabr** [comment]
Thanks for the tip, should be fixed now.

**Comment by f4dvk** [comment]
Thanks for the implementation. :-).
Stephane.
